CREATE TABLE MEMBER (
ID BIGINT NOT NULL,
USERNAME VARCHAR(10) NOT NULL,
PASSWORD VARCHAR(32) NOT NULL,
PRIMARY KEY (ID)
);
CREATE TABLE MEMBER_ROLE (
MEMBER_ID BIGINT NOT NULL,
ROLE VARCHAR(10) NOT NULL,
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID)
);

INSERT INTO MEMBER (ID,USERNAME,PASSWORD) VALUES  (1,'shahbaz','password');
INSERT INTO MEMBER (ID,USERNAME,PASSWORD) VALUES  (2,'deepa','password');
INSERT INTO MEMBER (ID,USERNAME,PASSWORD) VALUES  (3,'arijit','password');

INSERT INTO MEMBER_ROLE (MEMBER_ID,ROLE) VALUES (1,'ROLE_ADMIN');
INSERT INTO MEMBER_ROLE (MEMBER_ID,ROLE) VALUES (2,'ROLE_USER');
INSERT INTO MEMBER_ROLE (MEMBER_ID,ROLE) VALUES (3,'ROLE_USER');

SELECT USERNAME,PASSWORD,'TRUE' AS ENABLED FROM MEMBER WHERE USERNAME = 'shahbaz';

SELECT MEMBER.USERNAME, MEMBER_ROLE.ROLE AS AUTHORITIES 
FROM MEMBER,MEMBER_ROLE
WHERE MEMBER.USERNAME = ? AND MEMBER.ID=MEMBER_ROLE.MEMBER_ID;


UPDATE MEMBER SET PASSWORD = MD5('password') WHERE ID =1;
UPDATE MEMBER SET PASSWORD = MD5('password') WHERE ID =2;
UPDATE MEMBER SET PASSWORD = MD5('password') WHERE ID =3;

